test:
  dialect: postgres
  database: tasktracker_test
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

development:
  dialect: postgres
  database: tasktracker_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: tasktracker_production
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5
